services:
  frontend:
    build: .
    image: bandoncaddy:latest
    container_name: caddy
    init: true
    restart: unless-stopped
    volumes:
      - .:/app
      - static-data:/vol/static
      - media-data:/vol/media
    environment:
      DJANGO_CSRF_TRUSTED_ORIGINS: 'http://localhost:5000'

  frontend-proxy:
    image: nginx:latest
    container_name: deadginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-data:/vol/static:ro
      - media-data:/vol/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      frontend:
        condition: service_started

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email debboutr@gmail.com -d debbout.info --agree-tos

volumes:
  media-data:
  static-data:
